language: rust

matrix:
  include:
    - rust: stable
      script:
        - cargo test
        - cargo run --example serde
        - cargo run --example any

    - rust: nightly
      script:
        - cargo test --features nightly
